import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>                      
        <div className="pagina-principal">
          <div >
            <header> 
              <h1 className="header"> espaçoVip </h1>
            </header>              
            {children}                    
          </div>  
          <div className="menu">
            <h1>Teste</h1>
          </div>
        </div>
      </body>
    </html>
  );
}
